# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chisei_pb2 as chisei__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chisei_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChiseiServiceStub:
    """--- Service ---

    Governed decisions for agent operations: context, policy, budgets, routing,
    evaluation, approvals, and learning. Agent runtimes remain replaceable
    clients of this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckBudget = channel.unary_unary(
                '/chisei.ChiseiService/CheckBudget',
                request_serializer=chisei__pb2.CheckBudgetRequest.SerializeToString,
                response_deserializer=chisei__pb2.CheckBudgetResponse.FromString,
                _registered_method=True)
        self.RecordUsage = channel.unary_unary(
                '/chisei.ChiseiService/RecordUsage',
                request_serializer=chisei__pb2.RecordUsageRequest.SerializeToString,
                response_deserializer=chisei__pb2.RecordUsageResponse.FromString,
                _registered_method=True)
        self.SetBudgetLimit = channel.unary_unary(
                '/chisei.ChiseiService/SetBudgetLimit',
                request_serializer=chisei__pb2.SetBudgetLimitRequest.SerializeToString,
                response_deserializer=chisei__pb2.SetBudgetLimitResponse.FromString,
                _registered_method=True)
        self.RecordPortfolioObservation = channel.unary_unary(
                '/chisei.ChiseiService/RecordPortfolioObservation',
                request_serializer=chisei__pb2.RecordPortfolioObservationRequest.SerializeToString,
                response_deserializer=chisei__pb2.RecordPortfolioObservationResponse.FromString,
                _registered_method=True)
        self.GetPortfolioFrontier = channel.unary_unary(
                '/chisei.ChiseiService/GetPortfolioFrontier',
                request_serializer=chisei__pb2.GetPortfolioFrontierRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetPortfolioFrontierResponse.FromString,
                _registered_method=True)
        self.SetPortfolioObjective = channel.unary_unary(
                '/chisei.ChiseiService/SetPortfolioObjective',
                request_serializer=chisei__pb2.SetPortfolioObjectiveRequest.SerializeToString,
                response_deserializer=chisei__pb2.SetPortfolioObjectiveResponse.FromString,
                _registered_method=True)
        self.AllocatePortfolio = channel.unary_unary(
                '/chisei.ChiseiService/AllocatePortfolio',
                request_serializer=chisei__pb2.AllocatePortfolioRequest.SerializeToString,
                response_deserializer=chisei__pb2.AllocatePortfolioResponse.FromString,
                _registered_method=True)
        self.SetNamespacePolicy = channel.unary_unary(
                '/chisei.ChiseiService/SetNamespacePolicy',
                request_serializer=chisei__pb2.SetNamespacePolicyRequest.SerializeToString,
                response_deserializer=chisei__pb2.SetNamespacePolicyResponse.FromString,
                _registered_method=True)
        self.ResolvePolicy = channel.unary_unary(
                '/chisei.ChiseiService/ResolvePolicy',
                request_serializer=chisei__pb2.ResolvePolicyRequest.SerializeToString,
                response_deserializer=chisei__pb2.ResolvePolicyResponse.FromString,
                _registered_method=True)
        self.CheckEgress = channel.unary_unary(
                '/chisei.ChiseiService/CheckEgress',
                request_serializer=chisei__pb2.CheckEgressRequest.SerializeToString,
                response_deserializer=chisei__pb2.CheckEgressResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_unary(
                '/chisei.ChiseiService/RunPipeline',
                request_serializer=chisei__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=chisei__pb2.RunPipelineResponse.FromString,
                _registered_method=True)
        self.ListPipelineRuns = channel.unary_unary(
                '/chisei.ChiseiService/ListPipelineRuns',
                request_serializer=chisei__pb2.ListPipelineRunsRequest.SerializeToString,
                response_deserializer=chisei__pb2.ListPipelineRunsResponse.FromString,
                _registered_method=True)
        self.RecordSampleObservation = channel.unary_unary(
                '/chisei.ChiseiService/RecordSampleObservation',
                request_serializer=chisei__pb2.RecordSampleObservationRequest.SerializeToString,
                response_deserializer=chisei__pb2.RecordSampleObservationResponse.FromString,
                _registered_method=True)
        self.RecordGatewayAudit = channel.unary_unary(
                '/chisei.ChiseiService/RecordGatewayAudit',
                request_serializer=chisei__pb2.RecordGatewayAuditRequest.SerializeToString,
                response_deserializer=chisei__pb2.RecordGatewayAuditResponse.FromString,
                _registered_method=True)
        self.PlanExecution = channel.unary_unary(
                '/chisei.ChiseiService/PlanExecution',
                request_serializer=chisei__pb2.PlanExecutionRequest.SerializeToString,
                response_deserializer=chisei__pb2.PlanExecutionResponse.FromString,
                _registered_method=True)
        self.ExecutePlan = channel.unary_unary(
                '/chisei.ChiseiService/ExecutePlan',
                request_serializer=chisei__pb2.ExecutePlanRequest.SerializeToString,
                response_deserializer=chisei__pb2.ExecutePlanResponse.FromString,
                _registered_method=True)
        self.ExecutePlanStream = channel.unary_stream(
                '/chisei.ChiseiService/ExecutePlanStream',
                request_serializer=chisei__pb2.ExecutePlanRequest.SerializeToString,
                response_deserializer=chisei__pb2.ExecutePlanStreamEvent.FromString,
                _registered_method=True)
        self.ReportOperationEvent = channel.unary_unary(
                '/chisei.ChiseiService/ReportOperationEvent',
                request_serializer=chisei__pb2.ReportOperationEventRequest.SerializeToString,
                response_deserializer=chisei__pb2.ReportOperationEventResponse.FromString,
                _registered_method=True)
        self.AuthorizeOperationReporter = channel.unary_unary(
                '/chisei.ChiseiService/AuthorizeOperationReporter',
                request_serializer=chisei__pb2.AuthorizeOperationReporterRequest.SerializeToString,
                response_deserializer=chisei__pb2.AuthorizeOperationReporterResponse.FromString,
                _registered_method=True)
        self.GetOperationReceipt = channel.unary_unary(
                '/chisei.ChiseiService/GetOperationReceipt',
                request_serializer=chisei__pb2.GetOperationReceiptRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetOperationReceiptResponse.FromString,
                _registered_method=True)
        self.ReserveGatewayRequestAlias = channel.unary_unary(
                '/chisei.ChiseiService/ReserveGatewayRequestAlias',
                request_serializer=chisei__pb2.ReserveGatewayRequestAliasRequest.SerializeToString,
                response_deserializer=chisei__pb2.ReserveGatewayRequestAliasResponse.FromString,
                _registered_method=True)
        self.ClaimGatewayRequestAliasDispatch = channel.unary_unary(
                '/chisei.ChiseiService/ClaimGatewayRequestAliasDispatch',
                request_serializer=chisei__pb2.ClaimGatewayRequestAliasDispatchRequest.SerializeToString,
                response_deserializer=chisei__pb2.ClaimGatewayRequestAliasDispatchResponse.FromString,
                _registered_method=True)
        self.GetAffinity = channel.unary_unary(
                '/chisei.ChiseiService/GetAffinity',
                request_serializer=chisei__pb2.GetAffinityRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetAffinityResponse.FromString,
                _registered_method=True)
        self.CreateEvalSuite = channel.unary_unary(
                '/chisei.ChiseiService/CreateEvalSuite',
                request_serializer=chisei__pb2.CreateEvalSuiteRequest.SerializeToString,
                response_deserializer=chisei__pb2.CreateEvalSuiteResponse.FromString,
                _registered_method=True)
        self.ListEvalSuites = channel.unary_unary(
                '/chisei.ChiseiService/ListEvalSuites',
                request_serializer=chisei__pb2.ListEvalSuitesRequest.SerializeToString,
                response_deserializer=chisei__pb2.ListEvalSuitesResponse.FromString,
                _registered_method=True)
        self.GetEvalSuite = channel.unary_unary(
                '/chisei.ChiseiService/GetEvalSuite',
                request_serializer=chisei__pb2.GetEvalSuiteRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetEvalSuiteResponse.FromString,
                _registered_method=True)
        self.CreateEvalRun = channel.unary_unary(
                '/chisei.ChiseiService/CreateEvalRun',
                request_serializer=chisei__pb2.CreateEvalRunRequest.SerializeToString,
                response_deserializer=chisei__pb2.CreateEvalRunResponse.FromString,
                _registered_method=True)
        self.GetEvalRun = channel.unary_unary(
                '/chisei.ChiseiService/GetEvalRun',
                request_serializer=chisei__pb2.GetEvalRunRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetEvalRunResponse.FromString,
                _registered_method=True)
        self.ListEvalRuns = channel.unary_unary(
                '/chisei.ChiseiService/ListEvalRuns',
                request_serializer=chisei__pb2.ListEvalRunsRequest.SerializeToString,
                response_deserializer=chisei__pb2.ListEvalRunsResponse.FromString,
                _registered_method=True)
        self.TrackEvalIteration = channel.unary_unary(
                '/chisei.ChiseiService/TrackEvalIteration',
                request_serializer=chisei__pb2.TrackEvalIterationRequest.SerializeToString,
                response_deserializer=chisei__pb2.TrackEvalIterationResponse.FromString,
                _registered_method=True)
        self.GetLatestEvalIteration = channel.unary_unary(
                '/chisei.ChiseiService/GetLatestEvalIteration',
                request_serializer=chisei__pb2.GetLatestEvalIterationRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetLatestEvalIterationResponse.FromString,
                _registered_method=True)
        self.ListEvalIterations = channel.unary_unary(
                '/chisei.ChiseiService/ListEvalIterations',
                request_serializer=chisei__pb2.ListEvalIterationsRequest.SerializeToString,
                response_deserializer=chisei__pb2.ListEvalIterationsResponse.FromString,
                _registered_method=True)
        self.CompareRuns = channel.unary_unary(
                '/chisei.ChiseiService/CompareRuns',
                request_serializer=chisei__pb2.CompareRunsRequest.SerializeToString,
                response_deserializer=chisei__pb2.CompareRunsResponse.FromString,
                _registered_method=True)
        self.GetEvidenceContextGate = channel.unary_unary(
                '/chisei.ChiseiService/GetEvidenceContextGate',
                request_serializer=chisei__pb2.GetEvidenceContextGateRequest.SerializeToString,
                response_deserializer=chisei__pb2.GetEvidenceContextGateResponse.FromString,
                _registered_method=True)
        self.EvalVariance = channel.unary_unary(
                '/chisei.ChiseiService/EvalVariance',
                request_serializer=chisei__pb2.EvalVarianceRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvalVarianceResponse.FromString,
                _registered_method=True)
        self.EvalModelCompare = channel.unary_unary(
                '/chisei.ChiseiService/EvalModelCompare',
                request_serializer=chisei__pb2.EvalModelCompareRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvalModelCompareResponse.FromString,
                _registered_method=True)
        self.EvolveSuggest = channel.unary_unary(
                '/chisei.ChiseiService/EvolveSuggest',
                request_serializer=chisei__pb2.EvolveSuggestRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveSuggestResponse.FromString,
                _registered_method=True)
        self.EvolveEnhance = channel.unary_unary(
                '/chisei.ChiseiService/EvolveEnhance',
                request_serializer=chisei__pb2.EvolveEnhanceRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveEnhanceResponse.FromString,
                _registered_method=True)
        self.EvolveRecommend = channel.unary_unary(
                '/chisei.ChiseiService/EvolveRecommend',
                request_serializer=chisei__pb2.EvolveRecommendRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveRecommendResponse.FromString,
                _registered_method=True)
        self.EvolveReport = channel.unary_unary(
                '/chisei.ChiseiService/EvolveReport',
                request_serializer=chisei__pb2.EvolveReportRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveReportResponse.FromString,
                _registered_method=True)
        self.EvolvePatterns = channel.unary_unary(
                '/chisei.ChiseiService/EvolvePatterns',
                request_serializer=chisei__pb2.EvolvePatternsRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolvePatternsResponse.FromString,
                _registered_method=True)
        self.EvolveVariance = channel.unary_unary(
                '/chisei.ChiseiService/EvolveVariance',
                request_serializer=chisei__pb2.EvolveVarianceRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveVarianceResponse.FromString,
                _registered_method=True)
        self.EvolveAbResults = channel.unary_unary(
                '/chisei.ChiseiService/EvolveAbResults',
                request_serializer=chisei__pb2.EvolveAbResultsRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveAbResultsResponse.FromString,
                _registered_method=True)
        self.EvolveTemplates = channel.unary_unary(
                '/chisei.ChiseiService/EvolveTemplates',
                request_serializer=chisei__pb2.EvolveTemplatesRequest.SerializeToString,
                response_deserializer=chisei__pb2.EvolveTemplatesResponse.FromString,
                _registered_method=True)


class ChiseiServiceServicer:
    """--- Service ---

    Governed decisions for agent operations: context, policy, budgets, routing,
    evaluation, approvals, and learning. Agent runtimes remain replaceable
    clients of this service.
    """

    def CheckBudget(self, request, context):
        """Budget
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBudgetLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPortfolioObservation(self, request, context):
        """Intelligence portfolio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolioFrontier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPortfolioObjective(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocatePortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNamespacePolicy(self, request, context):
        """Model Policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolvePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckEgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Pipeline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPipelineRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordSampleObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordGatewayAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanExecution(self, request, context):
        """Native governed entry path. Planning resolves policy, context, routing,
        budget, and evaluation state before a provider call is allowed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePlan(self, request, context):
        """Executes a previously governed plan through the selected provider adapter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePlanStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportOperationEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeOperationReporter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveGatewayRequestAlias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimGatewayRequestAliasDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAffinity(self, request, context):
        """Affinity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvalSuite(self, request, context):
        """Eval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvalSuites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvalSuite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvalRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvalRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvalRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackEvalIteration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestEvalIteration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvalIterations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvidenceContextGate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvalVariance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvalModelCompare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveSuggest(self, request, context):
        """Evolve
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveEnhance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveRecommend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolvePatterns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveVariance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveAbResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvolveTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChiseiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBudget,
                    request_deserializer=chisei__pb2.CheckBudgetRequest.FromString,
                    response_serializer=chisei__pb2.CheckBudgetResponse.SerializeToString,
            ),
            'RecordUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsage,
                    request_deserializer=chisei__pb2.RecordUsageRequest.FromString,
                    response_serializer=chisei__pb2.RecordUsageResponse.SerializeToString,
            ),
            'SetBudgetLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBudgetLimit,
                    request_deserializer=chisei__pb2.SetBudgetLimitRequest.FromString,
                    response_serializer=chisei__pb2.SetBudgetLimitResponse.SerializeToString,
            ),
            'RecordPortfolioObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPortfolioObservation,
                    request_deserializer=chisei__pb2.RecordPortfolioObservationRequest.FromString,
                    response_serializer=chisei__pb2.RecordPortfolioObservationResponse.SerializeToString,
            ),
            'GetPortfolioFrontier': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolioFrontier,
                    request_deserializer=chisei__pb2.GetPortfolioFrontierRequest.FromString,
                    response_serializer=chisei__pb2.GetPortfolioFrontierResponse.SerializeToString,
            ),
            'SetPortfolioObjective': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPortfolioObjective,
                    request_deserializer=chisei__pb2.SetPortfolioObjectiveRequest.FromString,
                    response_serializer=chisei__pb2.SetPortfolioObjectiveResponse.SerializeToString,
            ),
            'AllocatePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocatePortfolio,
                    request_deserializer=chisei__pb2.AllocatePortfolioRequest.FromString,
                    response_serializer=chisei__pb2.AllocatePortfolioResponse.SerializeToString,
            ),
            'SetNamespacePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNamespacePolicy,
                    request_deserializer=chisei__pb2.SetNamespacePolicyRequest.FromString,
                    response_serializer=chisei__pb2.SetNamespacePolicyResponse.SerializeToString,
            ),
            'ResolvePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolvePolicy,
                    request_deserializer=chisei__pb2.ResolvePolicyRequest.FromString,
                    response_serializer=chisei__pb2.ResolvePolicyResponse.SerializeToString,
            ),
            'CheckEgress': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckEgress,
                    request_deserializer=chisei__pb2.CheckEgressRequest.FromString,
                    response_serializer=chisei__pb2.CheckEgressResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=chisei__pb2.RunPipelineRequest.FromString,
                    response_serializer=chisei__pb2.RunPipelineResponse.SerializeToString,
            ),
            'ListPipelineRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPipelineRuns,
                    request_deserializer=chisei__pb2.ListPipelineRunsRequest.FromString,
                    response_serializer=chisei__pb2.ListPipelineRunsResponse.SerializeToString,
            ),
            'RecordSampleObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordSampleObservation,
                    request_deserializer=chisei__pb2.RecordSampleObservationRequest.FromString,
                    response_serializer=chisei__pb2.RecordSampleObservationResponse.SerializeToString,
            ),
            'RecordGatewayAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordGatewayAudit,
                    request_deserializer=chisei__pb2.RecordGatewayAuditRequest.FromString,
                    response_serializer=chisei__pb2.RecordGatewayAuditResponse.SerializeToString,
            ),
            'PlanExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanExecution,
                    request_deserializer=chisei__pb2.PlanExecutionRequest.FromString,
                    response_serializer=chisei__pb2.PlanExecutionResponse.SerializeToString,
            ),
            'ExecutePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlan,
                    request_deserializer=chisei__pb2.ExecutePlanRequest.FromString,
                    response_serializer=chisei__pb2.ExecutePlanResponse.SerializeToString,
            ),
            'ExecutePlanStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecutePlanStream,
                    request_deserializer=chisei__pb2.ExecutePlanRequest.FromString,
                    response_serializer=chisei__pb2.ExecutePlanStreamEvent.SerializeToString,
            ),
            'ReportOperationEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOperationEvent,
                    request_deserializer=chisei__pb2.ReportOperationEventRequest.FromString,
                    response_serializer=chisei__pb2.ReportOperationEventResponse.SerializeToString,
            ),
            'AuthorizeOperationReporter': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeOperationReporter,
                    request_deserializer=chisei__pb2.AuthorizeOperationReporterRequest.FromString,
                    response_serializer=chisei__pb2.AuthorizeOperationReporterResponse.SerializeToString,
            ),
            'GetOperationReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationReceipt,
                    request_deserializer=chisei__pb2.GetOperationReceiptRequest.FromString,
                    response_serializer=chisei__pb2.GetOperationReceiptResponse.SerializeToString,
            ),
            'ReserveGatewayRequestAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveGatewayRequestAlias,
                    request_deserializer=chisei__pb2.ReserveGatewayRequestAliasRequest.FromString,
                    response_serializer=chisei__pb2.ReserveGatewayRequestAliasResponse.SerializeToString,
            ),
            'ClaimGatewayRequestAliasDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimGatewayRequestAliasDispatch,
                    request_deserializer=chisei__pb2.ClaimGatewayRequestAliasDispatchRequest.FromString,
                    response_serializer=chisei__pb2.ClaimGatewayRequestAliasDispatchResponse.SerializeToString,
            ),
            'GetAffinity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAffinity,
                    request_deserializer=chisei__pb2.GetAffinityRequest.FromString,
                    response_serializer=chisei__pb2.GetAffinityResponse.SerializeToString,
            ),
            'CreateEvalSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvalSuite,
                    request_deserializer=chisei__pb2.CreateEvalSuiteRequest.FromString,
                    response_serializer=chisei__pb2.CreateEvalSuiteResponse.SerializeToString,
            ),
            'ListEvalSuites': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvalSuites,
                    request_deserializer=chisei__pb2.ListEvalSuitesRequest.FromString,
                    response_serializer=chisei__pb2.ListEvalSuitesResponse.SerializeToString,
            ),
            'GetEvalSuite': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvalSuite,
                    request_deserializer=chisei__pb2.GetEvalSuiteRequest.FromString,
                    response_serializer=chisei__pb2.GetEvalSuiteResponse.SerializeToString,
            ),
            'CreateEvalRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvalRun,
                    request_deserializer=chisei__pb2.CreateEvalRunRequest.FromString,
                    response_serializer=chisei__pb2.CreateEvalRunResponse.SerializeToString,
            ),
            'GetEvalRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvalRun,
                    request_deserializer=chisei__pb2.GetEvalRunRequest.FromString,
                    response_serializer=chisei__pb2.GetEvalRunResponse.SerializeToString,
            ),
            'ListEvalRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvalRuns,
                    request_deserializer=chisei__pb2.ListEvalRunsRequest.FromString,
                    response_serializer=chisei__pb2.ListEvalRunsResponse.SerializeToString,
            ),
            'TrackEvalIteration': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackEvalIteration,
                    request_deserializer=chisei__pb2.TrackEvalIterationRequest.FromString,
                    response_serializer=chisei__pb2.TrackEvalIterationResponse.SerializeToString,
            ),
            'GetLatestEvalIteration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestEvalIteration,
                    request_deserializer=chisei__pb2.GetLatestEvalIterationRequest.FromString,
                    response_serializer=chisei__pb2.GetLatestEvalIterationResponse.SerializeToString,
            ),
            'ListEvalIterations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvalIterations,
                    request_deserializer=chisei__pb2.ListEvalIterationsRequest.FromString,
                    response_serializer=chisei__pb2.ListEvalIterationsResponse.SerializeToString,
            ),
            'CompareRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareRuns,
                    request_deserializer=chisei__pb2.CompareRunsRequest.FromString,
                    response_serializer=chisei__pb2.CompareRunsResponse.SerializeToString,
            ),
            'GetEvidenceContextGate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvidenceContextGate,
                    request_deserializer=chisei__pb2.GetEvidenceContextGateRequest.FromString,
                    response_serializer=chisei__pb2.GetEvidenceContextGateResponse.SerializeToString,
            ),
            'EvalVariance': grpc.unary_unary_rpc_method_handler(
                    servicer.EvalVariance,
                    request_deserializer=chisei__pb2.EvalVarianceRequest.FromString,
                    response_serializer=chisei__pb2.EvalVarianceResponse.SerializeToString,
            ),
            'EvalModelCompare': grpc.unary_unary_rpc_method_handler(
                    servicer.EvalModelCompare,
                    request_deserializer=chisei__pb2.EvalModelCompareRequest.FromString,
                    response_serializer=chisei__pb2.EvalModelCompareResponse.SerializeToString,
            ),
            'EvolveSuggest': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveSuggest,
                    request_deserializer=chisei__pb2.EvolveSuggestRequest.FromString,
                    response_serializer=chisei__pb2.EvolveSuggestResponse.SerializeToString,
            ),
            'EvolveEnhance': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveEnhance,
                    request_deserializer=chisei__pb2.EvolveEnhanceRequest.FromString,
                    response_serializer=chisei__pb2.EvolveEnhanceResponse.SerializeToString,
            ),
            'EvolveRecommend': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveRecommend,
                    request_deserializer=chisei__pb2.EvolveRecommendRequest.FromString,
                    response_serializer=chisei__pb2.EvolveRecommendResponse.SerializeToString,
            ),
            'EvolveReport': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveReport,
                    request_deserializer=chisei__pb2.EvolveReportRequest.FromString,
                    response_serializer=chisei__pb2.EvolveReportResponse.SerializeToString,
            ),
            'EvolvePatterns': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolvePatterns,
                    request_deserializer=chisei__pb2.EvolvePatternsRequest.FromString,
                    response_serializer=chisei__pb2.EvolvePatternsResponse.SerializeToString,
            ),
            'EvolveVariance': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveVariance,
                    request_deserializer=chisei__pb2.EvolveVarianceRequest.FromString,
                    response_serializer=chisei__pb2.EvolveVarianceResponse.SerializeToString,
            ),
            'EvolveAbResults': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveAbResults,
                    request_deserializer=chisei__pb2.EvolveAbResultsRequest.FromString,
                    response_serializer=chisei__pb2.EvolveAbResultsResponse.SerializeToString,
            ),
            'EvolveTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.EvolveTemplates,
                    request_deserializer=chisei__pb2.EvolveTemplatesRequest.FromString,
                    response_serializer=chisei__pb2.EvolveTemplatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chisei.ChiseiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chisei.ChiseiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChiseiService:
    """--- Service ---

    Governed decisions for agent operations: context, policy, budgets, routing,
    evaluation, approvals, and learning. Agent runtimes remain replaceable
    clients of this service.
    """

    @staticmethod
    def CheckBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/CheckBudget',
            chisei__pb2.CheckBudgetRequest.SerializeToString,
            chisei__pb2.CheckBudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/RecordUsage',
            chisei__pb2.RecordUsageRequest.SerializeToString,
            chisei__pb2.RecordUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBudgetLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/SetBudgetLimit',
            chisei__pb2.SetBudgetLimitRequest.SerializeToString,
            chisei__pb2.SetBudgetLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordPortfolioObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/RecordPortfolioObservation',
            chisei__pb2.RecordPortfolioObservationRequest.SerializeToString,
            chisei__pb2.RecordPortfolioObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolioFrontier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetPortfolioFrontier',
            chisei__pb2.GetPortfolioFrontierRequest.SerializeToString,
            chisei__pb2.GetPortfolioFrontierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPortfolioObjective(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/SetPortfolioObjective',
            chisei__pb2.SetPortfolioObjectiveRequest.SerializeToString,
            chisei__pb2.SetPortfolioObjectiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocatePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/AllocatePortfolio',
            chisei__pb2.AllocatePortfolioRequest.SerializeToString,
            chisei__pb2.AllocatePortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNamespacePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/SetNamespacePolicy',
            chisei__pb2.SetNamespacePolicyRequest.SerializeToString,
            chisei__pb2.SetNamespacePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolvePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ResolvePolicy',
            chisei__pb2.ResolvePolicyRequest.SerializeToString,
            chisei__pb2.ResolvePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckEgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/CheckEgress',
            chisei__pb2.CheckEgressRequest.SerializeToString,
            chisei__pb2.CheckEgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/RunPipeline',
            chisei__pb2.RunPipelineRequest.SerializeToString,
            chisei__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPipelineRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ListPipelineRuns',
            chisei__pb2.ListPipelineRunsRequest.SerializeToString,
            chisei__pb2.ListPipelineRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordSampleObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/RecordSampleObservation',
            chisei__pb2.RecordSampleObservationRequest.SerializeToString,
            chisei__pb2.RecordSampleObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordGatewayAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/RecordGatewayAudit',
            chisei__pb2.RecordGatewayAuditRequest.SerializeToString,
            chisei__pb2.RecordGatewayAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/PlanExecution',
            chisei__pb2.PlanExecutionRequest.SerializeToString,
            chisei__pb2.PlanExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ExecutePlan',
            chisei__pb2.ExecutePlanRequest.SerializeToString,
            chisei__pb2.ExecutePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePlanStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chisei.ChiseiService/ExecutePlanStream',
            chisei__pb2.ExecutePlanRequest.SerializeToString,
            chisei__pb2.ExecutePlanStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportOperationEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ReportOperationEvent',
            chisei__pb2.ReportOperationEventRequest.SerializeToString,
            chisei__pb2.ReportOperationEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizeOperationReporter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/AuthorizeOperationReporter',
            chisei__pb2.AuthorizeOperationReporterRequest.SerializeToString,
            chisei__pb2.AuthorizeOperationReporterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetOperationReceipt',
            chisei__pb2.GetOperationReceiptRequest.SerializeToString,
            chisei__pb2.GetOperationReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveGatewayRequestAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ReserveGatewayRequestAlias',
            chisei__pb2.ReserveGatewayRequestAliasRequest.SerializeToString,
            chisei__pb2.ReserveGatewayRequestAliasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimGatewayRequestAliasDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ClaimGatewayRequestAliasDispatch',
            chisei__pb2.ClaimGatewayRequestAliasDispatchRequest.SerializeToString,
            chisei__pb2.ClaimGatewayRequestAliasDispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAffinity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetAffinity',
            chisei__pb2.GetAffinityRequest.SerializeToString,
            chisei__pb2.GetAffinityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEvalSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/CreateEvalSuite',
            chisei__pb2.CreateEvalSuiteRequest.SerializeToString,
            chisei__pb2.CreateEvalSuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvalSuites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ListEvalSuites',
            chisei__pb2.ListEvalSuitesRequest.SerializeToString,
            chisei__pb2.ListEvalSuitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvalSuite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetEvalSuite',
            chisei__pb2.GetEvalSuiteRequest.SerializeToString,
            chisei__pb2.GetEvalSuiteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEvalRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/CreateEvalRun',
            chisei__pb2.CreateEvalRunRequest.SerializeToString,
            chisei__pb2.CreateEvalRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvalRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetEvalRun',
            chisei__pb2.GetEvalRunRequest.SerializeToString,
            chisei__pb2.GetEvalRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvalRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ListEvalRuns',
            chisei__pb2.ListEvalRunsRequest.SerializeToString,
            chisei__pb2.ListEvalRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackEvalIteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/TrackEvalIteration',
            chisei__pb2.TrackEvalIterationRequest.SerializeToString,
            chisei__pb2.TrackEvalIterationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestEvalIteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetLatestEvalIteration',
            chisei__pb2.GetLatestEvalIterationRequest.SerializeToString,
            chisei__pb2.GetLatestEvalIterationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvalIterations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/ListEvalIterations',
            chisei__pb2.ListEvalIterationsRequest.SerializeToString,
            chisei__pb2.ListEvalIterationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/CompareRuns',
            chisei__pb2.CompareRunsRequest.SerializeToString,
            chisei__pb2.CompareRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvidenceContextGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/GetEvidenceContextGate',
            chisei__pb2.GetEvidenceContextGateRequest.SerializeToString,
            chisei__pb2.GetEvidenceContextGateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvalVariance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvalVariance',
            chisei__pb2.EvalVarianceRequest.SerializeToString,
            chisei__pb2.EvalVarianceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvalModelCompare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvalModelCompare',
            chisei__pb2.EvalModelCompareRequest.SerializeToString,
            chisei__pb2.EvalModelCompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveSuggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveSuggest',
            chisei__pb2.EvolveSuggestRequest.SerializeToString,
            chisei__pb2.EvolveSuggestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveEnhance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveEnhance',
            chisei__pb2.EvolveEnhanceRequest.SerializeToString,
            chisei__pb2.EvolveEnhanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveRecommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveRecommend',
            chisei__pb2.EvolveRecommendRequest.SerializeToString,
            chisei__pb2.EvolveRecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveReport',
            chisei__pb2.EvolveReportRequest.SerializeToString,
            chisei__pb2.EvolveReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolvePatterns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolvePatterns',
            chisei__pb2.EvolvePatternsRequest.SerializeToString,
            chisei__pb2.EvolvePatternsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveVariance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveVariance',
            chisei__pb2.EvolveVarianceRequest.SerializeToString,
            chisei__pb2.EvolveVarianceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveAbResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveAbResults',
            chisei__pb2.EvolveAbResultsRequest.SerializeToString,
            chisei__pb2.EvolveAbResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvolveTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chisei.ChiseiService/EvolveTemplates',
            chisei__pb2.EvolveTemplatesRequest.SerializeToString,
            chisei__pb2.EvolveTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
